package com.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * AccountTrxFinal generated by hbm2java
 */
@Entity
@Table(name = "account_trx_final", schema = "public")
public class AccountTrxFinal implements java.io.Serializable {

	private int sirano;
	private Integer status;
	private Integer accountno;
	private Integer amount;
	private String transactiontype;

	public AccountTrxFinal() {
	}

	public AccountTrxFinal(int sirano) {
		this.sirano = sirano;
	}

	public AccountTrxFinal(int sirano, Integer status, Integer accountno, Integer amount, String transactiontype) {
		this.sirano = sirano;
		this.status = status;
		this.accountno = accountno;
		this.amount = amount;
		this.transactiontype = transactiontype;
	}

	@Id

	@Column(name = "sirano", unique = true, nullable = false)
	public int getSirano() {
		return this.sirano;
	}

	public void setSirano(int sirano) {
		this.sirano = sirano;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "accountno")
	public Integer getAccountno() {
		return this.accountno;
	}

	public void setAccountno(Integer accountno) {
		this.accountno = accountno;
	}

	@Column(name = "amount")
	public Integer getAmount() {
		return this.amount;
	}

	public void setAmount(Integer amount) {
		this.amount = amount;
	}

	@Column(name = "transactiontype", length = 1)
	public String getTransactiontype() {
		return this.transactiontype;
	}

	public void setTransactiontype(String transactiontype) {
		this.transactiontype = transactiontype;
	}

}
